import Link from "next/link";
import { Chrome } from "../components/Chrome";
import { readRepoFile, listRepoDir } from "@/lib/repo";
import { renderMarkdown } from "@/lib/markdown";
import {
  parseScouts,
  freshness,
  freshnessBadge,
  reportDate,
  extractFlagSummary,
  type Freshness,
  type FlagSummary,
} from "@/lib/scouts";

export const revalidate = 60;

// Scout reports are named drift-YYYY-MM-DD.md / audit-YYYY-MM-DD.md.
const DRIFT_RE = /^drift-\d{4}-\d{2}-\d{2}\.md$/;
const AUDIT_RE = /^audit-\d{4}-\d{2}-\d{2}\.md$/;

const FRESH_LABEL: Record<Freshness, string> = {
  fresh: "fresh",
  aging: "aging",
  stale: "stale",
  never: "never",
};

// One scout cell → a colored badge with its date (or "never").
function FreshCell({ cell, today }: { cell: string; today: string }) {
  const f = freshness(cell, today);
  const date = reportDate(cell);
  return (
    <span className={`badge ${freshnessBadge(f)}`}>
      {date ?? FRESH_LABEL[f]}
    </span>
  );
}

// The lifted FLAG summary of one report, or an honest note that none parsed.
function FlagBlock({
  kind,
  file,
  summary,
}: {
  kind: string;
  file: string | null;
  summary: FlagSummary | null;
}) {
  if (!file || !summary) {
    return (
      <div className="card">
        <h3>
          {kind}
          <span className="badge">none yet</span>
        </h3>
        <div className="meta">
          No {kind.toLowerCase()} report in _governance/reports/ yet. Scouts write
          the first one on their next run.
        </div>
      </div>
    );
  }
  return (
    <div className="card" style={{ borderLeft: "3px solid var(--warn)" }}>
      <h3>
        {kind}
        <Link href={`/reports/${encodeURIComponent(file.replace(/\.md$/, ""))}`}>
          <span className="badge brass">{file.replace(/\.md$/, "")}</span>
        </Link>
      </h3>
      {summary.found ? (
        <div
          className="prose table-scroll"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(summary.body || "_(no flags listed)_") }}
        />
      ) : (
        <div className="meta">
          This report has no parsable FLAG summary section — open the full report
          to read it.
        </div>
      )}
    </div>
  );
}

export default async function ScoutsPage() {
  const today = new Date().toISOString().slice(0, 10);

  const [dashboardMd, reportFiles] = await Promise.all([
    readRepoFile("DASHBOARD.md"),
    listRepoDir("_governance/reports"),
  ]);

  const scouts = parseScouts(dashboardMd);

  const driftFiles = reportFiles.filter((f) => DRIFT_RE.test(f)).sort().reverse();
  const auditFiles = reportFiles.filter((f) => AUDIT_RE.test(f)).sort().reverse();

  const latestDrift = driftFiles[0] ?? null;
  const latestAudit = auditFiles[0] ?? null;

  // Read only the most-recent drift + audit for FLAG surfacing (not every file).
  const [driftMd, auditMd] = await Promise.all([
    latestDrift ? readRepoFile(`_governance/reports/${latestDrift}`) : Promise.resolve(null),
    latestAudit ? readRepoFile(`_governance/reports/${latestAudit}`) : Promise.resolve(null),
  ]);

  const driftFlags = driftMd ? extractFlagSummary(driftMd) : null;
  const auditFlags = auditMd ? extractFlagSummary(auditMd) : null;

  // Reader list: drift + audit reports, newest first, capped at 30.
  const readable = [...driftFiles, ...auditFiles].sort().reverse().slice(0, 30);

  return (
    <Chrome title="Scouts" sub="governance-scout coverage &amp; flags" active="/ops">
      {/* FLAG surfacing — the whole point: flags visible without opening files. */}
      <div className="section-head">
        <h2>Flags</h2>
        <span className="meta">latest drift &amp; audit</span>
      </div>
      <FlagBlock kind="Drift" file={latestDrift} summary={driftFlags} />
      <FlagBlock kind="Audit" file={latestAudit} summary={auditFlags} />

      {/* Coverage table — per governed repo, freshness-colored. */}
      <div className="section-head">
        <h2>Coverage</h2>
        <span className="meta">
          {scouts.generated ? `dashboard ${scouts.generated}` : "DASHBOARD.md"}
        </span>
      </div>
      {scouts.rows.length === 0 ? (
        <div className="card">
          <div className="meta">
            No governance-scout table found in DASHBOARD.md. It is generated by
            generate.py from the per-repo scout reports.
          </div>
        </div>
      ) : (
        <div className="prose table-scroll">
          <table>
            <thead>
              <tr>
                <th>repo</th>
                <th>latest drift</th>
                <th>latest audit</th>
              </tr>
            </thead>
            <tbody>
              {scouts.rows.map((r) => (
                <tr key={r.repo}>
                  <td className="mono">{r.repo}</td>
                  <td>
                    <FreshCell cell={r.latestDrift} today={today} />
                  </td>
                  <td>
                    <FreshCell cell={r.latestAudit} today={today} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      <div className="card">
        <div className="meta">
          Freshness is read from each report&apos;s date:{" "}
          <span className="badge good">green</span> ≤2 days,{" "}
          <span className="badge warn">amber</span> ≤7 days,{" "}
          <span className="badge bad">red</span> older or never. The dashboard
          table is a swept snapshot; its own generation date bounds how current
          this view is.
        </div>
      </div>

      {/* Report reader — only strandworks-ops reports are reachable from the
          cockpit token (SPEC Slice-1 #5); other repos keep their reports locally. */}
      <div className="section-head">
        <h2>Reports</h2>
        <span className="meta">strandworks-ops · latest {readable.length}</span>
      </div>
      {readable.length === 0 ? (
        <div className="card">
          <div className="meta">
            No drift-*/audit-* reports in _governance/reports/ yet. The daily
            drift-check writes the first one on its next run.
          </div>
        </div>
      ) : (
        <div className="ledger">
          {readable.map((f) => (
            <Link
              key={f}
              href={`/reports/${encodeURIComponent(f.replace(/\.md$/, ""))}`}
              className="l-row"
            >
              <span className="l-date">{f.startsWith("audit") ? "audit" : "drift"}</span>
              <span className="l-name mono" style={{ fontSize: 12.5 }}>
                {f}
              </span>
              <span className="l-amount dim">→</span>
            </Link>
          ))}
        </div>
      )}

      {/* Scout infrastructure — static, from the governance rituals + claude-ops. */}
      <div className="section-head">
        <h2>Infrastructure</h2>
      </div>
      <div className="card">
        <div className="meta">
          Scouts run on the claude-ops droplet — daily 06:10 CT Mon–Sat
          (drift-check), Sunday 06:10 (weekly drift + full audit). Reports are
          proposals for the owner; scouts fix nothing.
        </div>
      </div>
    </Chrome>
  );
}
